"""Loop V1 Package D: final real vertical acceptance for one fragment.

This module implements — offline, against synthetic substitutes only — the
frozen capability a later authorized run executes exactly once: a locally
assembled fragment plus one already-read public source plus at most five
explicitly selected local context cards go through exactly ONE DeepSeek
V4 Pro call (inventory and final synthesis in a single response), then a
local deterministic renderer publishes one Obsidian-compatible
``碎片认知结果`` draft that stays ``lifecycle_status: draft`` +
``evidence_level: unverified``.  There is no second model and no second
call: the single call is NOT an independent model review, the draft
boundary says so verbatim (不构成独立模型复核，必须人工确认), and the
result remains draft+unverified pending human confirmation.

The core entry never scans disk, never reads environment variables,
Keychain, real fragments, real notes, or the network.  The trusted caller
assembles every input object; this module only validates, binds, reserves,
and publishes.  Vendor adaptation (single official-host JSON call, strict
response/usage validation, no retry/fallback) is reused from
``fragment_loop.cognitive_real_pilot``; the persistent reservation ledger
follows the same reserve-before-send, unknown-send-counts, no-recovery
discipline, additionally bound to the session identity so any drift of
fragment, URL, source, context cards, quote catalog, plan version, or
authorization fails closed instead of拼接旧结果.

Plan v3 replaced model-transcribed verbatim quotes with a deterministic
local quote catalog, killing the v2 failure class
(``stage_result_invalid:inference_quote_source_unbound:2``).  Plan v4
removed model-filled ``evidence_refs``/``source_id`` bindings, killing the
v3 failure class (``stage_result_invalid:claim_quote_source_ref_missing:3``).
The v4 real block was ``stage_result_invalid:v1_inventory_invalid``: the
first DeepSeek send is permanently consumed, the second was never sent,
and the remaining authorization is exactly one DeepSeek call with GLM
already exhausted at 3/3.  Plan v5 is the final offline收口 under that
budget: one single-call wire schema in which only ``claims`` is a
required key-authenticity field (non-empty; per-claim
``claim_id``/``text``/``quote_id``/``verdict`` plus optional
``context_refs``, all strictly validated against the deterministic quote
catalog and the local context ids), while every other section —
``inventory``, ``literal_facts``, ``structural_inferences``, ``unknowns``,
``research_questions``, the four views, and ``synthesis`` — is an optional
display field limited to the shapes string / list[string] / fixed view
object.  Missing or empty optional sections are rendered as the explicit
local placeholder 本次模型未生成，待人工补充 — never fabricated, never a
reason to reject an already-sent result; provided-but-illegal optional
content still fails closed.  The top level allows only the predefined
fields; any extra key, any model-emitted ``evidence_refs``/``source_id``
binding field, free-text quote, or self-score field fails closed on
shape.  Media/privacy/forbidden-phrase scanning stays strict.
``not_covered`` claims must anchor on ``F0`` with empty ``context_refs``;
every other verdict's evidence relation is strictly checked as quote
layer + context refs, and every evidence ref shown in the public draft or
sidecar is generated by local pure functions — never model free text.

Plan v5 is frozen under ``loop-v1-final-acceptance-plan-v5`` and a
versioned v5 authorization phrase.  The retired v1/v2/v3/v4 phrases are
rejected with zero side effects, and a v1/v2/v3/v4 ledger at the same
path — including the v4 real-failure ledger — is never opened as
resumable, completable, or reusable: it fails closed with a fixed
plan/session identity mismatch and is left byte-for-byte untouched
(completed or failed ledgers are never migrated, continued, spliced, or
rewritten).  The external model plan is exactly one DeepSeek V4 Pro call;
total budget is 10000 input / 7000 output tokens with the exact provider
limit deepseek_v4_pro=1 and zero GLM calls.
"""

from __future__ import annotations

import fcntl
import hashlib
import json
import os
import re
import stat
import tempfile
import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from pathlib import Path, PurePosixPath
from urllib.parse import urlsplit

from fragment_loop.cognitive_real_pilot import (
    ModelAdapter,
    ModelCallError,
    PilotExecutionError,
)

# Plan v5 freezes the single-call contract: plans v1 (no required
# attribution), v2 (model-transcribed verbatim quotes), v3 (model-filled
# evidence_refs duplicating what the quote layer already determines) and
# v4 (two-call plan whose real block
# ``stage_result_invalid:v1_inventory_invalid`` permanently consumed the
# first DeepSeek send) are permanently retired: their authorization
# phrases are rejected before any manifest read, ledger touch, credential
# access, model call, or output write, and any v1/v2/v3/v4 ledger at the
# same path fails closed with a fixed plan/session identity mismatch —
# never migrated, rewritten, spliced, or deleted.  A v5 run requires a
# fresh ledger.
PLAN_VERSION = "loop-v1-final-acceptance-plan-v5"
AUTHORIZATION = (
    "NIGO_AUTHORIZE_LOOP_V1_FINAL_ACCEPTANCE_PLAN_V5_ONE_FRAGMENT_DEEPSEEK1"
)

_STAGE_ORDER = ("combined",)
_STAGE_BUDGETS = {
    "combined": ("deepseek_v4_pro", 10_000, 7_000),
}
_PROVIDER_LIMITS = {"deepseek_v4_pro": 1}
_PROVIDER_MODELS = {"deepseek_v4_pro": "deepseek-v4-pro"}
_TOTAL_INPUT_LIMIT = 10_000
_TOTAL_OUTPUT_LIMIT = 7_000
_MAX_CONTEXT_CARDS = 5

# The exact local placeholder rendered for every optional display section
# the model did not generate.  It is a local string, never model output,
# and it never counts as generated or verified content.
MISSING_SECTION_PLACEHOLDER = "本次模型未生成，待人工补充"

# Quote catalog bounds: the catalog is the only channel through which
# verbatim external text reaches the model, so it must stay small,
# deterministic, and incapable of swallowing arbitrary private material.
# Only the fragment text and the public source body may enter it; local
# context cards never do.  Over-long bodies or over-large catalogs fail
# closed at input validation instead of being truncated (truncation would
# silently hide evidence from the model while still citing the source).
_MAX_SOURCE_BODY_CHARS = 8_000
_MAX_CATALOG_ENTRIES = 49  # 1 fragment anchor + at most 48 source segments
_MAX_SEGMENT_CHARS = 240

_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$")
_SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
_VERDICTS = {"supported", "partially_supported", "contradicted", "not_covered"}

# Phrases that would falsely upgrade evidence: treating a media second-hand
# page as an independently verified paper, treating local notes as external
# evidence, claiming publication/asset promotion, or claiming private reads.
_FORBIDDEN_PHRASES = (
    "已独立核验原论文",
    "已独立验证原论文",
    "已核验原论文",
    "已验证原论文",
    "独立核验了原论文",
    "独立验证了原论文",
    "本地笔记是外部证据",
    "本地笔记作为外部证据",
    "本地笔记可作为外部证据",
    "本地上下文是外部证据",
    "本地上下文作为外部证据",
    "已提升为资产",
    "已发布",
    "已验证通过",
    "已扫描 Obsidian",
    "已读取 Obsidian",
    "来自 Obsidian",
    "根据私人笔记",
)


class FinalAcceptanceInputError(ValueError):
    """The assembled input, manifest, or session identity is not acceptable."""


class FinalAcceptanceBudgetError(ValueError):
    """The frozen single-call plan cannot safely consume another call."""


class FinalAcceptanceExecutionError(RuntimeError):
    """A planned stage failed or the draft cannot be safely published."""


@dataclass(frozen=True)
class SourceProfile:
    """Caller-frozen allowlist for the one public URL."""

    allowed_host: str
    allowed_path_prefix: str


@dataclass(frozen=True)
class PublicSourceCard:
    """The one already-read public source, a media second-hand page."""

    source_id: str
    title: str
    publisher: str
    published_at: str
    body: str
    source_type: str
    scope: str
    fetched_at: str


@dataclass(frozen=True)
class ContextCard:
    """One explicitly selected local context excerpt (user cognition only)."""

    context_id: str
    title: str
    excerpt: str
    ref: str
    content_sha256: str


@dataclass(frozen=True)
class AssembledInput:
    """Everything the trusted caller assembled; this module scans nothing."""

    fragment_id: str
    fragment_text: str
    fragment_content_sha256: str
    sanitized_public_url: str
    public_source: PublicSourceCard
    context_cards: tuple[ContextCard, ...]
    profile: SourceProfile
    output_dir: Path
    ledger_path: Path


def _nonempty_text(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _canonical_hash(value: object) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _string_list(value: object, *, allow_empty: bool = True) -> list[str] | None:
    if not isinstance(value, list) or any(not _nonempty_text(item) for item in value):
        return None
    if not allow_empty and not value:
        return None
    return value


def check_public_url(url: object, profile: SourceProfile) -> tuple[str, ...]:
    """Fail closed on any query/fragment/userinfo, non-https, or host/path drift."""
    if not _nonempty_text(url):
        return ("url_invalid",)
    text = str(url)
    if any(character.isspace() for character in text) or "%" in text:
        return ("url_invalid",)
    try:
        split = urlsplit(text)
    except ValueError:
        return ("url_invalid",)
    errors: list[str] = []
    if split.scheme != "https":
        errors.append("url_not_https")
    if split.username is not None or split.password is not None or "@" in split.netloc:
        errors.append("url_userinfo_not_allowed")
    if split.query:
        errors.append("url_query_not_allowed")
    if split.fragment:
        errors.append("url_fragment_not_allowed")
    if split.port is not None:
        errors.append("url_port_not_allowed")
    if split.hostname != profile.allowed_host:
        errors.append("url_host_drift")
    path = split.path or ""
    if not path.startswith(profile.allowed_path_prefix):
        errors.append("url_path_drift")
    elif ".." in PurePosixPath(path).parts:
        errors.append("url_path_escape")
    return tuple(errors)


def _validate_source_card(card: PublicSourceCard) -> tuple[str, ...]:
    errors: list[str] = []
    if not _ID_PATTERN.match(card.source_id):
        errors.append("source_id_invalid")
    source_fields = (
        "title",
        "publisher",
        "published_at",
        "body",
        "source_type",
        "scope",
        "fetched_at",
    )
    for field in source_fields:
        if not _nonempty_text(getattr(card, field)):
            errors.append(f"source_{field}_invalid")
    if len(card.body) > _MAX_SOURCE_BODY_CHARS:
        errors.append("source_body_too_long")
    return tuple(errors)


def _validate_context_card(card: ContextCard) -> tuple[str, ...]:
    errors: list[str] = []
    if not _ID_PATTERN.match(card.context_id):
        errors.append("context_id_invalid")
    if not _nonempty_text(card.title) or not _nonempty_text(card.excerpt):
        errors.append("context_text_invalid")
    ref = card.ref
    if not _nonempty_text(ref) or "://" in ref or "\\" in ref or "~" in ref:
        errors.append("context_ref_invalid")
    else:
        normalized = PurePosixPath(ref)
        parts = normalized.parts
        if (
            normalized.is_absolute()
            or ".." in parts
            or any(part in ("", ".") for part in parts)
            or str(normalized) != ref
        ):
            errors.append("context_ref_invalid")
    if not _SHA256_PATTERN.match(card.content_sha256):
        errors.append("context_hash_invalid")
    elif _sha256_text(card.excerpt) != card.content_sha256:
        errors.append("context_hash_mismatch")
    return tuple(errors)


def validate_assembled_input(value: AssembledInput) -> tuple[str, ...]:
    """Pure validation of the caller-assembled input; no filesystem access."""
    errors: list[str] = []
    if not _ID_PATTERN.match(value.fragment_id):
        errors.append("fragment_id_invalid")
    if not _nonempty_text(value.fragment_text):
        errors.append("fragment_text_invalid")
    if not _SHA256_PATTERN.match(value.fragment_content_sha256):
        errors.append("fragment_hash_invalid")
    elif _sha256_text(value.fragment_text) != value.fragment_content_sha256:
        errors.append("fragment_hash_mismatch")
    errors.extend(check_public_url(value.sanitized_public_url, value.profile))
    errors.extend(_validate_source_card(value.public_source))
    cards = value.context_cards
    if len(cards) > _MAX_CONTEXT_CARDS:
        errors.append("context_cards_too_many")
    seen: set[str] = set()
    for index, card in enumerate(cards):
        card_errors = _validate_context_card(card)
        errors.extend(f"context_{index}:{error}" for error in card_errors)
        if card.context_id in seen:
            errors.append(f"context_{index}:context_id_duplicate")
        seen.add(card.context_id)
    if value.public_source.source_id in seen:
        errors.append("source_id_collides_with_context")
    if not errors and len(build_quote_catalog(value).entries) > _MAX_CATALOG_ENTRIES:
        errors.append("quote_catalog_too_large")
    return tuple(errors)


def context_card_ids(value: AssembledInput) -> frozenset[str]:
    """The only ids a model may put in ``context_refs`` — local cards only.

    The public source id is deliberately excluded: the model never binds
    the source by name; the source ref is derived locally from the quote
    layer instead.
    """
    return frozenset(card.context_id for card in value.context_cards)


# --- Deterministic quote catalog ----------------------------------------
#
# The catalog is built by a pure local function from exactly two inputs:
# the fragment text and the already-read public source body.  The fragment
# contributes one fixed anchor ``F0``; the body is split into stable,
# ordered, non-empty segments.  URLs are treated as atomic tokens so a
# sentence split never breaks a link apart; empty segments are dropped,
# duplicate segments keep only their first occurrence, and over-long
# segments are split on secondary punctuation and then hard-cut at a fixed
# width.  Local ContextCards never enter the catalog: private context is
# user cognition background, not external evidence.

_FRAGMENT_QUOTE_ID = "F0"
_SENTENCE_ENDS = frozenset("。！？!?；;\n")
_SUB_BREAKS = frozenset("，,、：:")
_URL_PATTERN = re.compile(r"https?://[A-Za-z0-9\-._~:/?#@!$&*+,;=%\[\]]+")


@dataclass(frozen=True)
class QuoteEntry:
    """One catalog entry: a stable ID bound to verbatim text and its layer.

    ``layer`` is ``"fragment"`` for the fragment anchor, or the public
    source id owning this segment.  No other layer exists — in particular
    local context card ids are never a layer.
    """

    quote_id: str
    layer: str
    text: str


@dataclass(frozen=True)
class QuoteCatalog:
    """The deterministic verbatim quote catalog for one assembled input."""

    entries: tuple[QuoteEntry, ...]
    sha256: str

    def lookup(self, quote_id: object) -> QuoteEntry | None:
        if not isinstance(quote_id, str):
            return None
        for entry in self.entries:
            if entry.quote_id == quote_id:
                return entry
        return None


def _split_long_segment(text: str) -> list[str]:
    """Split an over-long segment deterministically: secondary punctuation
    first (delimiter kept at the end of each piece), then a fixed-width
    hard cut.  Segments within the limit pass through unchanged."""
    cleaned = text.strip()
    if not cleaned:
        return []
    if len(cleaned) <= _MAX_SEGMENT_CHARS:
        return [cleaned]
    pieces: list[str] = []
    current = ""
    for character in cleaned:
        current += character
        if character in _SUB_BREAKS:
            pieces.append(current)
            current = ""
    if current:
        pieces.append(current)
    result: list[str] = []
    for piece in pieces:
        part = piece.strip()
        if not part:
            continue
        while len(part) > _MAX_SEGMENT_CHARS:
            result.append(part[:_MAX_SEGMENT_CHARS])
            part = part[_MAX_SEGMENT_CHARS:]
        result.append(part)
    return result


def _split_source_segments(body: str) -> list[str]:
    """Split the public source body into stable, ordered, non-empty,
    deduplicated verbatim segments.  URLs stay atomic."""
    tokens: list[str] = []
    position = 0
    for match in _URL_PATTERN.finditer(body):
        if match.start() > position:
            tokens.append(body[position : match.start()])
        tokens.append(match.group(0))
        position = match.end()
    if position < len(body):
        tokens.append(body[position:])
    segments: list[str] = []
    seen: set[str] = set()

    def emit(pieces: list[str]) -> None:
        for piece in pieces:
            cleaned = piece.strip()
            # Drop whitespace-empty and pure-punctuation segments: a catalog
            # entry must carry at least one letter/digit/CJK character.
            if not any(character.isalnum() for character in cleaned):
                continue
            if cleaned in seen:
                continue
            seen.add(cleaned)
            segments.append(cleaned)

    for token in tokens:
        if _URL_PATTERN.fullmatch(token):
            emit([token])
            continue
        current = ""
        for character in token:
            current += character
            if character in _SENTENCE_ENDS:
                emit(_split_long_segment(current))
                current = ""
        if current.strip():
            emit(_split_long_segment(current))
    return segments


def build_quote_catalog(value: AssembledInput) -> QuoteCatalog:
    """Build the deterministic quote catalog; same input, same catalog."""
    entries = [
        QuoteEntry(
            quote_id=_FRAGMENT_QUOTE_ID,
            layer="fragment",
            text=value.fragment_text,
        )
    ]
    source_id = value.public_source.source_id
    for index, segment in enumerate(
        _split_source_segments(value.public_source.body), start=1
    ):
        entries.append(
            QuoteEntry(
                quote_id=f"{source_id}-q{index:02d}",
                layer=source_id,
                text=segment,
            )
        )
    sha256 = _canonical_hash(
        [
            {"quote_id": entry.quote_id, "layer": entry.layer, "text": entry.text}
            for entry in entries
        ]
    )
    return QuoteCatalog(entries=tuple(entries), sha256=sha256)


def session_identity(value: AssembledInput, authorization: str) -> str:
    """Bind fragment, URL, source, context cards, catalog, plan, authorization."""
    return _canonical_hash(
        {
            "fragment_content_sha256": value.fragment_content_sha256,
            "sanitized_public_url": value.sanitized_public_url,
            "public_source_sha256": _canonical_hash(asdict(value.public_source)),
            "context_cards_sha256": _canonical_hash(
                [asdict(card) for card in value.context_cards]
            ),
            "quote_catalog_sha256": build_quote_catalog(value).sha256,
            "plan_version": PLAN_VERSION,
            "authorization_sha256": _sha256_text(authorization),
        }
    )


_MANIFEST_KEYS = {
    "fragment_id",
    "fragment_text",
    "fragment_content_sha256",
    "sanitized_public_url",
    "public_source",
    "context_cards",
    "source_profile",
    "output_dir",
    "ledger_path",
}
_SOURCE_KEYS = {
    "source_id",
    "title",
    "publisher",
    "published_at",
    "body",
    "source_type",
    "scope",
    "fetched_at",
}
_CONTEXT_KEYS = {"context_id", "title", "excerpt", "ref", "content_sha256"}
_PROFILE_KEYS = {"allowed_host", "allowed_path_prefix"}


def _operational_path(value: object, field: str) -> Path:
    if not _nonempty_text(value):
        raise FinalAcceptanceInputError(f"manifest_{field}_invalid")
    path = Path(str(value))
    if not path.is_absolute() or ".." in path.parts:
        raise FinalAcceptanceInputError(f"manifest_{field}_invalid")
    return path


def check_local_path_safety(path: Path, *, expect: str) -> tuple[str, ...]:
    """Reject any symlink or wrong-type component among existing components.

    ``expect`` is ``"file"`` or ``"dir"`` for the target itself.  A tail that
    does not exist yet is allowed, but from the nearest existing ancestor to
    the target no component may be a symlink, and every existing ancestor
    must be a real directory.
    """
    if not path.is_absolute():
        return ("path_not_absolute",)
    current = Path(path.anchor)
    parts = path.parts[1:]
    for index, part in enumerate(parts):
        current = current / part
        last = index == len(parts) - 1
        try:
            info = current.lstat()
        except OSError:
            break
        if stat.S_ISLNK(info.st_mode):
            return ("path_component_symlink",)
        if last:
            if expect == "dir" and not stat.S_ISDIR(info.st_mode):
                return ("path_target_not_directory",)
            if expect == "file" and not stat.S_ISREG(info.st_mode):
                return ("path_target_not_regular_file",)
        elif not stat.S_ISDIR(info.st_mode):
            return ("path_ancestor_not_directory",)
    return ()


def preflight_operational_paths(value: AssembledInput) -> tuple[str, ...]:
    """Symlink/type preflight for every on-disk path the run may touch.

    Covers the ledger file, the ledger lock file, the output directory, and
    through the ancestor walk the output directory's parent chain.  Runs
    before any ledger creation, credential read, or model call.
    """
    lock_path = value.ledger_path.with_name(f".{value.ledger_path.name}.lock")
    for path, expect in (
        (value.ledger_path, "file"),
        (lock_path, "file"),
        (value.output_dir, "dir"),
    ):
        errors = check_local_path_safety(path, expect=expect)
        if errors:
            return errors
    return ()


def _str_fields(raw: dict[str, object], keys: set[str], error: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for key in keys:
        value = raw[key]
        if not isinstance(value, str):
            raise FinalAcceptanceInputError(error)
        values[key] = value
    return values


def load_manifest(path: Path) -> AssembledInput:
    """Load the strict 0600 JSON manifest; any drift fails closed."""
    path_errors = check_local_path_safety(path, expect="file")
    if path_errors:
        raise FinalAcceptanceInputError(f"manifest_path_unsafe:{path_errors[0]}")
    try:
        info = path.lstat()
    except OSError as error:
        raise FinalAcceptanceInputError("manifest_unreadable") from error
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        raise FinalAcceptanceInputError("manifest_not_regular_file")
    if stat.S_IMODE(info.st_mode) != 0o600:
        raise FinalAcceptanceInputError("manifest_permissions_invalid")
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise FinalAcceptanceInputError("manifest_invalid") from error
    if not isinstance(loaded, dict) or set(loaded) != _MANIFEST_KEYS:
        raise FinalAcceptanceInputError("manifest_schema_invalid")
    top = _str_fields(
        loaded,
        {"fragment_id", "fragment_text", "fragment_content_sha256", "sanitized_public_url"},
        "manifest_schema_invalid",
    )
    source_raw = loaded["public_source"]
    if not isinstance(source_raw, dict) or set(source_raw) != _SOURCE_KEYS:
        raise FinalAcceptanceInputError("manifest_source_invalid")
    source = _str_fields(source_raw, _SOURCE_KEYS, "manifest_source_invalid")
    cards_raw = loaded["context_cards"]
    if not isinstance(cards_raw, list):
        raise FinalAcceptanceInputError("manifest_context_invalid")
    cards: list[ContextCard] = []
    for card_raw in cards_raw:
        if not isinstance(card_raw, dict) or set(card_raw) != _CONTEXT_KEYS:
            raise FinalAcceptanceInputError("manifest_context_invalid")
        cards.append(
            ContextCard(**_str_fields(card_raw, _CONTEXT_KEYS, "manifest_context_invalid"))
        )
    profile_raw = loaded["source_profile"]
    if not isinstance(profile_raw, dict) or set(profile_raw) != _PROFILE_KEYS:
        raise FinalAcceptanceInputError("manifest_profile_invalid")
    profile = _str_fields(profile_raw, _PROFILE_KEYS, "manifest_profile_invalid")
    assembled = AssembledInput(
        fragment_id=top["fragment_id"],
        fragment_text=top["fragment_text"],
        fragment_content_sha256=top["fragment_content_sha256"],
        sanitized_public_url=top["sanitized_public_url"],
        public_source=PublicSourceCard(**source),
        context_cards=tuple(cards),
        profile=SourceProfile(
            allowed_host=profile["allowed_host"],
            allowed_path_prefix=profile["allowed_path_prefix"],
        ),
        output_dir=_operational_path(loaded["output_dir"], "output_dir"),
        ledger_path=_operational_path(loaded["ledger_path"], "ledger_path"),
    )
    errors = validate_assembled_input(assembled)
    if errors:
        raise FinalAcceptanceInputError(f"manifest_rejected:{errors[0]}")
    return assembled


class SessionLedger:
    """Persistent reservation ledger bound to one exact session identity.

    Same discipline as the Pilot 1 ledger: reserve before send, unknown send
    counts as consumed, no retry, no recovery, no fallback; completed stages
    are reused on restart and an incomplete reservation blocks re-sending.
    Additionally the whole ledger fails closed when the session identity
    (fragment hash, sanitized URL, public source hash, context cards hash,
    quote catalog hash, plan version, authorization hash) drifts.
    """

    def __init__(
        self,
        path: Path,
        session: str,
        *,
        catalog: QuoteCatalog,
        context_ids: frozenset[str],
    ):
        self.path = path
        self._session = session
        self._catalog = catalog
        self._context_ids = context_ids
        self._lock_path = path.with_name(f".{path.name}.lock")

    @contextmanager
    def _locked(self) -> Iterator[None]:
        for candidate in (self._lock_path, self.path):
            path_errors = check_local_path_safety(candidate, expect="file")
            if path_errors:
                raise FinalAcceptanceBudgetError(
                    f"ledger_path_unsafe:{path_errors[0]}"
                )
        self.path.parent.mkdir(parents=True, exist_ok=True)
        descriptor = os.open(self._lock_path, os.O_CREAT | os.O_RDWR, 0o600)
        try:
            fcntl.flock(descriptor, fcntl.LOCK_EX)
            yield
        finally:
            fcntl.flock(descriptor, fcntl.LOCK_UN)
            os.close(descriptor)

    def _load(self) -> dict[str, object]:
        if not self.path.exists():
            return {
                "version": PLAN_VERSION,
                "session_identity": self._session,
                "reservations": [],
            }
        if self.path.is_symlink() or not self.path.is_file():
            raise FinalAcceptanceBudgetError("ledger_path_invalid")
        try:
            loaded = json.loads(self.path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
            raise FinalAcceptanceBudgetError("ledger_invalid") from error
        if (
            not isinstance(loaded, dict)
            or set(loaded) != {"version", "session_identity", "reservations"}
            or not isinstance(loaded.get("reservations"), list)
        ):
            raise FinalAcceptanceBudgetError("ledger_invalid")
        if loaded.get("version") != PLAN_VERSION:
            raise FinalAcceptanceBudgetError("ledger_plan_version_mismatch")
        if loaded.get("session_identity") != self._session:
            raise FinalAcceptanceBudgetError("ledger_identity_mismatch")
        return loaded

    def _write(self, state: dict[str, object]) -> None:
        payload = json.dumps(
            state, ensure_ascii=False, sort_keys=True, separators=(",", ":")
        )
        descriptor, temporary = tempfile.mkstemp(
            prefix=f".{self.path.name}.", dir=self.path.parent
        )
        try:
            os.fchmod(descriptor, 0o600)
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, self.path)
        except Exception:
            try:
                os.unlink(temporary)
            except FileNotFoundError:
                pass
            raise

    def reserve(
        self,
        stage: str,
        provider: str,
        input_tokens: int,
        output_tokens: int,
    ) -> str:
        expected = _STAGE_BUDGETS.get(stage)
        if expected is None:
            raise FinalAcceptanceBudgetError("stage_not_allowed")
        if expected != (provider, input_tokens, output_tokens):
            raise FinalAcceptanceBudgetError("stage_budget_mismatch")
        with self._locked():
            state = self._load()
            reservations = state["reservations"]
            assert isinstance(reservations, list)
            if any(
                isinstance(item, dict) and item.get("stage") == stage
                for item in reservations
            ):
                raise FinalAcceptanceBudgetError("stage_already_reserved")
            completed = {
                str(item.get("stage"))
                for item in reservations
                if isinstance(item, dict) and item.get("status") == "completed"
            }
            prior = _STAGE_ORDER[: _STAGE_ORDER.index(stage)]
            if any(previous not in completed for previous in prior):
                raise FinalAcceptanceBudgetError("stage_order_violation")
            provider_count = sum(
                1
                for item in reservations
                if isinstance(item, dict) and item.get("provider") == provider
            )
            if provider_count >= _PROVIDER_LIMITS[provider]:
                raise FinalAcceptanceBudgetError("provider_call_limit_reached")
            reserved_input = sum(
                int(item.get("reserved_input_tokens", 0))
                for item in reservations
                if isinstance(item, dict)
            )
            reserved_output = sum(
                int(item.get("reserved_output_tokens", 0))
                for item in reservations
                if isinstance(item, dict)
            )
            if (
                reserved_input + input_tokens > _TOTAL_INPUT_LIMIT
                or reserved_output + output_tokens > _TOTAL_OUTPUT_LIMIT
            ):
                raise FinalAcceptanceBudgetError("total_token_limit_reached")
            reservation_id = f"final-acceptance-{uuid.uuid4().hex}"
            reservations.append(
                {
                    "reservation_id": reservation_id,
                    "stage": stage,
                    "provider": provider,
                    "reserved_input_tokens": input_tokens,
                    "reserved_output_tokens": output_tokens,
                    "status": "reserved",
                }
            )
            self._write(state)
            return reservation_id

    def complete(
        self,
        reservation_id: str,
        *,
        model_claim: str,
        prompt_tokens: int,
        completion_tokens: int,
        result: dict[str, object],
    ) -> None:
        if (
            not _nonempty_text(model_claim)
            or not isinstance(prompt_tokens, int)
            or isinstance(prompt_tokens, bool)
            or prompt_tokens < 0
            or not isinstance(completion_tokens, int)
            or isinstance(completion_tokens, bool)
            or completion_tokens < 0
        ):
            raise FinalAcceptanceBudgetError("completion_evidence_invalid")
        with self._locked():
            state = self._load()
            reservations = state["reservations"]
            assert isinstance(reservations, list)
            matches = [
                item
                for item in reservations
                if isinstance(item, dict)
                and item.get("reservation_id") == reservation_id
            ]
            if len(matches) != 1:
                raise FinalAcceptanceBudgetError("reservation_not_found")
            reservation = matches[0]
            if reservation.get("status") != "reserved":
                raise FinalAcceptanceBudgetError("reservation_already_completed")
            if prompt_tokens > int(reservation["reserved_input_tokens"]) or (
                completion_tokens > int(reservation["reserved_output_tokens"])
            ):
                raise FinalAcceptanceBudgetError("observed_usage_out_of_bounds")
            provider = str(reservation["provider"])
            if model_claim != _PROVIDER_MODELS[provider]:
                raise FinalAcceptanceBudgetError("response_model_mismatch")
            errors = validate_combined_result(
                result,
                catalog=self._catalog,
                context_ids=self._context_ids,
            )
            if errors:
                raise FinalAcceptanceBudgetError(f"stage_result_invalid:{errors[0]}")
            reservation.update(
                {
                    "status": "completed",
                    "model_claim": model_claim,
                    "prompt_tokens": prompt_tokens,
                    "completion_tokens": completion_tokens,
                    "result": result,
                }
            )
            self._write(state)

    def fail(
        self,
        reservation_id: str,
        *,
        error_category: str,
        request_sent: bool | None,
    ) -> None:
        if (
            not _nonempty_text(error_category)
            or len(error_category) > 200
            or request_sent not in (True, False, None)
        ):
            raise FinalAcceptanceBudgetError("failure_evidence_invalid")
        with self._locked():
            state = self._load()
            reservations = state["reservations"]
            assert isinstance(reservations, list)
            matches = [
                item
                for item in reservations
                if isinstance(item, dict)
                and item.get("reservation_id") == reservation_id
            ]
            if len(matches) != 1 or matches[0].get("status") != "reserved":
                raise FinalAcceptanceBudgetError("reservation_not_pending")
            matches[0].update(
                {
                    "status": "failed",
                    "error_category": error_category,
                    "request_sent": request_sent,
                }
            )
            self._write(state)

    def stage_result(self, stage: str) -> dict[str, object] | None:
        with self._locked():
            state = self._load()
        reservations = state["reservations"]
        assert isinstance(reservations, list)
        matches = [
            item
            for item in reservations
            if isinstance(item, dict) and item.get("stage") == stage
        ]
        if len(matches) != 1 or matches[0].get("status") != "completed":
            return None
        result = matches[0].get("result")
        if not isinstance(result, dict):
            raise FinalAcceptanceBudgetError("ledger_invalid")
        return result

    def stage_reserved(self, stage: str) -> bool:
        with self._locked():
            state = self._load()
        reservations = state["reservations"]
        assert isinstance(reservations, list)
        return any(
            isinstance(item, dict) and item.get("stage") == stage
            for item in reservations
        )

    def view(self) -> dict[str, object]:
        with self._locked():
            state = self._load()
        reservations = state["reservations"]
        assert isinstance(reservations, list)
        return {
            "version": state["version"],
            "session_identity": state["session_identity"],
            "reservations": reservations,
            "reserved_input_tokens": sum(
                int(item.get("reserved_input_tokens", 0))
                for item in reservations
                if isinstance(item, dict)
            ),
            "reserved_output_tokens": sum(
                int(item.get("reserved_output_tokens", 0))
                for item in reservations
                if isinstance(item, dict)
            ),
            "provider_counts": {
                provider: sum(
                    1
                    for item in reservations
                    if isinstance(item, dict) and item.get("provider") == provider
                )
                for provider in _PROVIDER_LIMITS
            },
        }


def _source_json(value: AssembledInput) -> str:
    card = asdict(value.public_source)
    card["locator"] = value.sanitized_public_url
    return json.dumps(card, ensure_ascii=False, separators=(",", ":"))


def _context_json(value: AssembledInput) -> str:
    return json.dumps(
        [
            {
                "context_id": card.context_id,
                "title": card.title,
                "excerpt": card.excerpt,
                "ref": card.ref,
            }
            for card in value.context_cards
        ],
        ensure_ascii=False,
        separators=(",", ":"),
    )


def _catalog_json(catalog: QuoteCatalog) -> str:
    return json.dumps(
        [
            {"quote_id": entry.quote_id, "layer": entry.layer, "text": entry.text}
            for entry in catalog.entries
        ],
        ensure_ascii=False,
        separators=(",", ":"),
    )


def build_shared_context(value: AssembledInput, catalog: QuoteCatalog) -> str:
    """The only context the single-call prompt may contain."""
    return (
        "这是 Loop V1 最终真实纵向验收的单碎片单次调用任务。不得使用模型记忆补充事实；"
        "公开来源只能引用提供的 source_id；本地上下文只能引用提供的 context_id；"
        "逐字引用只能从给定目录选择 quote_id，不得自行生成或改写任何引文；"
        "证据绑定由本地系统按 quote_id 层与 context_refs 推导，你不得返回任何 "
        "evidence_refs 或 source_id 绑定字段。\n"
        f"原始碎片：{value.fragment_text}\n"
        "公开来源卡（媒体二手来源，未独立核验原论文）："
        f"{_source_json(value)}\n"
        "本地上下文卡（用户既有认知材料，不是外部事实来源，0-5 条）："
        f"{_context_json(value)}\n"
        "逐字引用目录（本地确定性构造，layer 为 fragment 或公开来源 source_id，"
        f"引用时只输出 quote_id）：{_catalog_json(catalog)}\n"
        "证据边界：公开页面属于媒体二手来源，其中转述的论文数字不得描述成已独立核验"
        "原论文；本地上下文是用户既有认知材料，不得当作独立外部证据或外部事实来源；"
        "本地 context_id 不是合法 quote_id 层级；禁止任何形式的模型自评分；不得声称"
        "内容已发布、已验证或已提升为资产。\n"
    )


def _combined_prompt(value: AssembledInput, catalog: QuoteCatalog) -> str:
    """The one and only model prompt: inventory and synthesis in one answer.

    The wire schema is deliberately minimal to keep the failure rate low:
    only ``claims`` is required; every other field is optional and limited
    to string / list[string] / fixed view object shapes.  The model is
    told to omit a field entirely when it cannot ground it, because the
    local renderer substitutes an explicit placeholder instead.
    """
    return build_shared_context(value, catalog) + (
        "你只有这一次调用：在同一次回答里完成第一版信息盘点与最终综合判断；"
        "没有第二模型复核，结论必须保持草稿口径。只输出一个 JSON 对象，顶层只允许"
        "以下字段，不允许任何其他字段。唯一必填字段是 "
        "claims[{claim_id,text,quote_id,verdict,context_refs?}]，至少一条；其余字段"
        "全部可选，无法确定就整个字段省略，不要编造、不要输出空字符串："
        "inventory（字符串，本轮信息盘点综合叙述）、literal_facts[string]、"
        "structural_inferences[string]、unknowns[string]、research_questions[string]、"
        "memory_view{analysis,uncertainty,context_refs?}、"
        "personal_view{analysis,uncertainty,context_refs?}、"
        "project_view{analysis,uncertainty,context_refs?}、"
        "frontier_view{analysis,uncertainty}、"
        "synthesis{judgment?,opportunities?[string],risks?[string],"
        "next_steps?[string],uncertainties?[string]}。"
        "所有 quote_id 必须是逐字引用目录中存在的 ID：fragment 锚点为 F0，公开来源"
        "句段为 source_id-qNN；本地 context_id 不是合法 quote_id。claim 不得返回 "
        "evidence_refs、source_id、basis 或任何逐字引文文本字段：公开来源绑定由"
        "系统按 quote_id 的 layer 本地推导；context_refs 可选，只能包含提供的 "
        "context_id，不得包含 source_id。verdict 只允许 supported、"
        "partially_supported、contradicted、not_covered；not_covered 的 quote_id "
        "必须为 F0 且 context_refs 必须为空；其余 verdict 的证据关系由 quote layer "
        "与 context_refs 共同构成，二者至少其一（quote_id 为 F0 时 context_refs 至少"
        "一条）。memory_view 是现有记忆视角，personal_view 是个人认知与偏好视角，"
        "project_view 是知识库与项目进展视角，三者只能基于本地上下文卡与碎片原文，"
        "context_refs 申报实际使用的本地卡，且必须说明它们属用户既有认知而非外部"
        "事实；本地卡为 0 条时必须整个省略 memory_view、personal_view 和 "
        "project_view，不得编造本地材料或用户偏好。frontier_view 是前沿行业／技术／科学"
        "视角，只能基于公开来源，公开来源绑定由系统完成，你不得返回任何引用字段。"
        "不得输出任何评分字段，不得输出任何逐字引文文本字段。"
    )


# v5 wire schema: the top level allows only these predefined fields.
# ``claims`` is the single required key-authenticity field; everything
# else is an optional display field.  Any other top-level key — including
# model-emitted evidence_refs/source_id bindings, free-text quote fields,
# or self-score fields — fails closed on shape.
_RESULT_REQUIRED_KEYS = {"claims"}
_RESULT_ALLOWED_KEYS = {
    "claims",
    "inventory",
    "literal_facts",
    "structural_inferences",
    "unknowns",
    "research_questions",
    "memory_view",
    "personal_view",
    "project_view",
    "frontier_view",
    "synthesis",
}
_LIST_DISPLAY_FIELDS = (
    "literal_facts",
    "structural_inferences",
    "unknowns",
    "research_questions",
)
_LOCAL_VIEW_FIELDS = ("memory_view", "personal_view", "project_view")
_VIEW_REQUIRED_KEYS = {"analysis", "uncertainty"}
_VIEW_ALLOWED_KEYS = _VIEW_REQUIRED_KEYS | {"context_refs"}
_FRONTIER_VIEW_KEYS = {"analysis", "uncertainty"}
_SYNTHESIS_ALLOWED_KEYS = {
    "judgment",
    "opportunities",
    "risks",
    "next_steps",
    "uncertainties",
}
_SYNTHESIS_LIST_FIELDS = ("opportunities", "risks", "next_steps", "uncertainties")


def _context_refs_of(item: dict[str, object]) -> list[str] | None:
    """Parse the optional ``context_refs`` field; missing means []."""
    raw = item.get("context_refs", [])
    return _string_list(raw, allow_empty=True)


def _check_context_refs(
    refs: list[str] | None, context_ids: frozenset[str]
) -> str | None:
    if refs is None:
        return "context_refs_invalid"
    for ref in refs:
        if ref not in context_ids:
            return f"unknown_context_ref:{ref}"
    return None


def _derived_source_ref(catalog: QuoteCatalog, quote_id: object) -> str | None:
    """Derive the public source ref from a quote_id's catalog layer.

    Pure local function: ``None`` for the fragment anchor (or an unknown
    id), otherwise the owning public source id.  The model never fills
    this in — v3's real block was the model omitting exactly this field.
    """
    entry = catalog.lookup(quote_id)
    if entry is None or entry.layer == "fragment":
        return None
    return entry.layer


def derived_claim_binding(
    catalog: QuoteCatalog, item: dict[str, object]
) -> dict[str, tuple[str, ...]]:
    """Locally derived evidence binding for one claim.

    Returns ``source_refs`` (0 or 1, derived from the quote layer) and
    ``context_refs`` (the validated local context ids the model declared).
    This is the only channel through which evidence refs reach the draft
    or the sidecar.
    """
    source = _derived_source_ref(catalog, item.get("quote_id"))
    context_refs = _context_refs_of(item) or []
    return {
        "source_refs": (source,) if source is not None else (),
        "context_refs": tuple(context_refs),
    }


def _forbidden_scan(value: object) -> tuple[str, ...]:
    serialized = json.dumps(value, ensure_ascii=False)
    return tuple(
        f"forbidden_claim:{phrase}"
        for phrase in _FORBIDDEN_PHRASES
        if phrase in serialized
    )


def _check_quote_id(
    quote_id: object,
    *,
    catalog: QuoteCatalog,
    kind: str,
    index: int,
) -> QuoteEntry | str:
    """Resolve a model-returned quote_id against the deterministic catalog.

    The model never emits verbatim text; it only picks catalog IDs.  Any ID
    missing from the catalog — a hallucinated ID, a layer-foreign ID such as
    a local ContextCard id, or a non-string value — fails closed with a
    fixed category.  The resolved entry carries the real verbatim text and
    its owning layer for downstream binding checks and rendering.
    """
    entry = catalog.lookup(quote_id)
    if entry is None:
        return f"{kind}_quote_id_unknown:{index}"
    return entry


_CLAIM_REQUIRED_KEYS = {"claim_id", "text", "quote_id", "verdict"}
_CLAIM_ALLOWED_KEYS = _CLAIM_REQUIRED_KEYS | {"context_refs"}


def _validate_claims(
    value: object, *, catalog: QuoteCatalog, context_ids: frozenset[str]
) -> tuple[str, ...]:
    """Strict validation of the only required key-authenticity field."""
    if not isinstance(value, list) or not value:
        return ("claims_invalid",)
    errors: list[str] = []
    seen_claims: set[str] = set()
    for index, claim in enumerate(value):
        # The model returns only quote_id plus optional context_refs;
        # evidence_refs/source_id bindings are system-derived, so any
        # model-emitted binding field fails closed on shape.
        if (
            not isinstance(claim, dict)
            or not _CLAIM_REQUIRED_KEYS <= set(claim)
            or not set(claim) <= _CLAIM_ALLOWED_KEYS
        ):
            errors.append(f"claim_invalid:{index}")
            continue
        claim_id = claim.get("claim_id")
        if not _nonempty_text(claim_id) or str(claim_id) in seen_claims:
            errors.append(f"claim_id_invalid:{index}")
        else:
            seen_claims.add(str(claim_id))
        resolved = _check_quote_id(
            claim.get("quote_id"), catalog=catalog, kind="claim", index=index
        )
        entry: QuoteEntry | None = None
        if isinstance(resolved, str):
            errors.append(resolved)
        else:
            entry = resolved
        context_refs = _context_refs_of(claim)
        ref_error = _check_context_refs(context_refs, context_ids)
        if ref_error is not None:
            errors.append(f"claim_context_refs_invalid:{index}:{ref_error}")
            context_refs = []
        if not _nonempty_text(claim.get("text")):
            errors.append(f"claim_text_invalid:{index}")
        verdict = claim.get("verdict")
        if verdict not in _VERDICTS:
            errors.append(f"claim_verdict_invalid:{index}")
        if verdict == "not_covered":
            # not_covered must anchor on the fragment itself and carry
            # no evidence: F0 only, empty context_refs.
            if entry is not None and entry.layer != "fragment":
                errors.append(f"not_covered_quote_not_fragment:{index}")
            if context_refs:
                errors.append(f"not_covered_has_context_refs:{index}")
        elif verdict in _VERDICTS:
            # The evidence relation is quote layer + context refs;
            # at least one must bind the claim.
            if entry is not None and entry.layer == "fragment" and not context_refs:
                errors.append(f"claim_unbound:{index}")
    return tuple(errors)


def validate_combined_result(
    value: object,
    *,
    catalog: QuoteCatalog,
    context_ids: frozenset[str],
) -> tuple[str, ...]:
    """Validate the single-call result without trusting its prose.

    Only ``claims`` is required.  Optional display fields are validated
    only when present: provided-but-illegal content fails closed, while a
    missing field is not an error at all — the renderer substitutes the
    explicit local placeholder instead.
    """
    if (
        not isinstance(value, dict)
        or not _RESULT_REQUIRED_KEYS <= set(value)
        or not set(value) <= _RESULT_ALLOWED_KEYS
    ):
        return ("result_shape_invalid",)
    errors: list[str] = list(
        _validate_claims(value["claims"], catalog=catalog, context_ids=context_ids)
    )
    inventory = value.get("inventory")
    if inventory is not None and not _nonempty_text(inventory):
        errors.append("inventory_invalid")
    for field in _LIST_DISPLAY_FIELDS:
        field_value = value.get(field)
        if field_value is not None and _string_list(field_value) is None:
            errors.append(f"{field}_invalid")
    for field in _LOCAL_VIEW_FIELDS:
        view = value.get(field)
        if view is None:
            continue
        if (
            not isinstance(view, dict)
            or not _VIEW_REQUIRED_KEYS <= set(view)
            or not set(view) <= _VIEW_ALLOWED_KEYS
        ):
            errors.append(f"{field}_invalid")
            continue
        if not _nonempty_text(view.get("analysis")) or not _nonempty_text(
            view.get("uncertainty")
        ):
            errors.append(f"{field}_text_invalid")
        ref_error = _check_context_refs(_context_refs_of(view), context_ids)
        if ref_error is not None:
            errors.append(f"{field}_context_refs_invalid:{ref_error}")
    frontier = value.get("frontier_view")
    if frontier is not None:
        # frontier_view is fixed to the public source; the system binds the
        # source_id, so any model-emitted ref field fails closed on shape.
        if not isinstance(frontier, dict) or set(frontier) != _FRONTIER_VIEW_KEYS:
            errors.append("frontier_view_invalid")
        elif not _nonempty_text(frontier.get("analysis")) or not _nonempty_text(
            frontier.get("uncertainty")
        ):
            errors.append("frontier_view_text_invalid")
    synthesis = value.get("synthesis")
    if synthesis is not None:
        if not isinstance(synthesis, dict) or not set(synthesis) <= (
            _SYNTHESIS_ALLOWED_KEYS
        ):
            errors.append("synthesis_invalid")
        else:
            judgment = synthesis.get("judgment")
            if judgment is not None and not _nonempty_text(judgment):
                errors.append("synthesis_judgment_invalid")
            for field in _SYNTHESIS_LIST_FIELDS:
                items = synthesis.get(field)
                if items is not None and _string_list(items) is None:
                    errors.append(f"synthesis_{field}_invalid")
    errors.extend(_forbidden_scan(value))
    return tuple(errors)


def _execute_stage(
    ledger: SessionLedger,
    *,
    stage: str,
    prompt: str,
    adapter: ModelAdapter,
) -> dict[str, object]:
    completed = ledger.stage_result(stage)
    if completed is not None:
        return completed
    if ledger.stage_reserved(stage):
        raise FinalAcceptanceExecutionError(f"{stage}_incomplete_blocks_retry")
    provider, input_limit, output_limit = _STAGE_BUDGETS[stage]
    reservation_id = ledger.reserve(stage, provider, input_limit, output_limit)
    try:
        reply = adapter(prompt, output_limit)
    except ModelCallError as error:
        ledger.fail(
            reservation_id,
            error_category=error.category,
            request_sent=error.request_sent,
        )
        raise FinalAcceptanceExecutionError(f"{stage}_call_failed") from None
    except PilotExecutionError as error:
        ledger.fail(
            reservation_id,
            error_category=str(error),
            request_sent=None,
        )
        raise FinalAcceptanceExecutionError(f"{stage}_call_failed") from None
    except Exception:
        ledger.fail(
            reservation_id,
            error_category="unexpected_adapter_failure",
            request_sent=None,
        )
        raise FinalAcceptanceExecutionError(f"{stage}_call_failed") from None
    try:
        ledger.complete(
            reservation_id,
            model_claim=reply.model_claim,
            prompt_tokens=reply.prompt_tokens,
            completion_tokens=reply.completion_tokens,
            result=reply.result,
        )
    except FinalAcceptanceBudgetError as error:
        ledger.fail(
            reservation_id,
            error_category=str(error),
            request_sent=True,
        )
        raise FinalAcceptanceExecutionError(f"{stage}_result_rejected") from None
    result: dict[str, object] = reply.result
    return result


def run_final_acceptance(
    value: AssembledInput,
    *,
    authorization: str,
    adapter: ModelAdapter,
) -> dict[str, object]:
    """Run the frozen one-call plan; wrong authorization is zero-effect."""
    if authorization != AUTHORIZATION:
        raise FinalAcceptanceExecutionError("authorization_required")
    errors = validate_assembled_input(value)
    if errors:
        raise FinalAcceptanceInputError(f"assembled_input_invalid:{errors[0]}")
    path_errors = preflight_operational_paths(value)
    if path_errors:
        raise FinalAcceptanceExecutionError(f"path_unsafe:{path_errors[0]}")
    catalog = build_quote_catalog(value)
    session = session_identity(value, authorization)
    ledger = SessionLedger(
        value.ledger_path,
        session,
        catalog=catalog,
        context_ids=context_card_ids(value),
    )
    result = _execute_stage(
        ledger,
        stage="combined",
        prompt=_combined_prompt(value, catalog),
        adapter=adapter,
    )
    return {
        "session_identity": session,
        "fragment_id": value.fragment_id,
        "quote_catalog_sha256": catalog.sha256,
        "result": result,
        "markdown": render_draft_markdown(value, session, catalog, result),
        "ledger": ledger.view(),
    }


def _render_frontmatter(fields: tuple[tuple[str, object], ...]) -> str:
    header = "\n".join(
        f"{key}: {json.dumps(field, ensure_ascii=False, separators=(',', ':'))}"
        for key, field in fields
    )
    return f"---\n{header}\n---\n"


def _quote_line(catalog: QuoteCatalog, quote_id: object) -> str:
    """Inject the real verbatim text for a model-chosen quote_id."""
    entry = catalog.lookup(quote_id)
    if entry is None:  # unreachable: validators ran first; fail closed anyway
        raise FinalAcceptanceExecutionError("quote_catalog_drift")
    return f"{entry.quote_id}（{entry.layer}）：{entry.text}"


def _binding_text(binding: dict[str, tuple[str, ...]]) -> str:
    """Render one locally derived binding; never model free text."""
    source = "、".join(binding["source_refs"]) or "无"
    contexts = "、".join(binding["context_refs"]) or "无"
    return f"公开来源 {source}；本地上下文 {contexts}"


def _display_list(result: dict[str, object], field: str) -> list[str] | None:
    """The model-provided display list, or ``None`` when missing or empty.

    ``None`` means the renderer must emit the explicit local placeholder;
    validators already rejected any provided-but-illegal shape.
    """
    raw = result.get(field)
    if not isinstance(raw, list) or not raw:
        return None
    return [str(item) for item in raw]


def render_draft_markdown(
    value: AssembledInput,
    session: str,
    catalog: QuoteCatalog,
    result: dict[str, object],
) -> str:
    """Render the validated single-call result into the draft-only note body.

    Fully deterministic and local: every verbatim quote in the output is
    injected from the local quote catalog, every evidence binding is
    derived by local pure functions from quote layers and declared
    context_refs — never from model-emitted refs or free-text citations —
    and every section the model did not generate is shown as the explicit
    local placeholder, never as fabricated or verified content.
    """
    context_ids = context_card_ids(value)
    if validate_combined_result(result, catalog=catalog, context_ids=context_ids):
        raise FinalAcceptanceExecutionError("result_invalid")
    placeholder = MISSING_SECTION_PLACEHOLDER
    title = f"碎片认知结果草稿：{value.fragment_text.strip()[:30]}"
    frontmatter = _render_frontmatter(
        (
            ("type", "碎片认知结果"),
            ("title", title),
            ("lifecycle_status", "draft"),
            ("evidence_level", "unverified"),
            ("user_confirmed", False),
            ("promoted_to_asset", False),
            ("paper_independently_verified", False),
            ("single_model_single_call", True),
            ("fragment_id", value.fragment_id),
            ("session_identity", session),
            ("quote_catalog_sha256", catalog.sha256),
            ("plan_version", PLAN_VERSION),
        )
    )
    source = value.public_source
    lines = [
        f"# {title}",
        "",
        "## 状态与边界",
        "",
        "- 本笔记是 `draft + unverified` 草稿：用户尚未确认，未提升为资产。",
        "- 全部模型内容来自同一模型 DeepSeek V4 Pro 的单次调用（盘点与综合同源）："
        "不构成独立模型复核，相关性风险未消除，使用前必须人工确认。",
        "- 公开页面是媒体二手来源：其中转述的论文数字未独立核验原论文。",
        "- 本地上下文是用户既有认知材料，不作为外部事实来源。",
        "- 全部逐字引用来自本地确定性引用目录，模型只选择了 quote_id。",
        "- 全部证据绑定（公开来源 source_id 与本地 context_id）由本地纯函数"
        "按 quote_id 层与申报的 context_refs 推导，模型不返回任何绑定字段。",
        f"- 标注「{placeholder}」的区块是本地占位：模型本次未产出该内容，"
        "系统不补写任何事实，也不代表该部分已验证。",
        "",
        "## 原始碎片",
        "",
        f"> {value.fragment_text}",
        "",
        "## 公开来源（媒体二手来源）",
        "",
        f"- **{source.source_id} · {source.title}**：{source.publisher}，"
        f"{source.published_at}，{value.sanitized_public_url}",
        f"  - 范围：{source.scope}",
        "",
        "## 本地上下文（用户既有认知材料）",
        "",
    ]
    if value.context_cards:
        for card in value.context_cards:
            lines.append(f"- **{card.context_id} · {card.title}**（引用：{card.ref}）")
    else:
        lines.append("- 本轮未选择本地上下文。")
    lines.extend(["", "## 逐字引用目录（本地确定性构造）", ""])
    for entry in catalog.entries:
        lines.append(f"- **{entry.quote_id}**（{entry.layer}）：{entry.text}")
    lines.extend(["", "## 信息盘点（单次 DeepSeek 调用）", ""])
    inventory = result.get("inventory")
    lines.append(str(inventory) if _nonempty_text(inventory) else placeholder)
    for heading, field in (
        ("字面事实", "literal_facts"),
        ("结构推断", "structural_inferences"),
        ("未知", "unknowns"),
        ("研究问题", "research_questions"),
    ):
        lines.extend(["", f"### {heading}", ""])
        items = _display_list(result, field)
        if items is None:
            lines.append(f"- {placeholder}")
        else:
            lines.extend(f"- {item}" for item in items)
    lines.extend(["", "## 主张与证据绑定（本地推导）", ""])
    claims = result["claims"]
    assert isinstance(claims, list)
    claim_bindings: dict[str, dict[str, tuple[str, ...]]] = {}
    for claim in claims:
        assert isinstance(claim, dict)
        binding = derived_claim_binding(catalog, claim)
        claim_bindings[str(claim["claim_id"])] = binding
        lines.append(
            f"- **{claim['claim_id']} · {claim['verdict']}**：{claim['text']}"
            f"（证据绑定（本地推导）：{_binding_text(binding)}；"
            f"原文 {_quote_line(catalog, claim['quote_id'])}）"
        )
    for heading, key in (
        ("现有记忆视角（仅基于本地上下文，属用户既有认知）", "memory_view"),
        ("个人认知与偏好视角（仅基于本地上下文，属用户既有认知）", "personal_view"),
        ("知识库与项目进展视角（仅基于本地材料）", "project_view"),
    ):
        lines.extend(["", f"## {heading}", ""])
        # No selected local card means there is no factual basis for any
        # memory, preference, or project claim.  Model prose is ignored even
        # when it was returned: the human-facing draft must not turn a
        # single-model guess into a user profile.
        if not value.context_cards:
            lines.append("本轮未选择本地上下文，无法形成该视角判断。")
            continue
        view = result.get(key)
        if not isinstance(view, dict):
            lines.append(placeholder)
            continue
        used = "、".join(_context_refs_of(view) or []) or "无"
        lines.append(str(view["analysis"]))
        lines.append(f"\n使用本地上下文（模型申报，仅限 context_id）：{used}")
        lines.append(f"\n不确定性：{view['uncertainty']}")
    lines.extend(["", "## 前沿行业／技术／科学视角（仅基于公开来源）", ""])
    frontier = result.get("frontier_view")
    if not isinstance(frontier, dict):
        lines.append(placeholder)
    else:
        lines.append(str(frontier["analysis"]))
        lines.append(f"\n证据绑定（本地推导，仅限公开来源）：{source.source_id}")
        lines.append(f"\n不确定性：{frontier['uncertainty']}")
    all_sources = sorted(
        {ref for binding in claim_bindings.values() for ref in binding["source_refs"]}
        | {source.source_id}
    )
    all_contexts = sorted(
        {ref for binding in claim_bindings.values() for ref in binding["context_refs"]}
    )
    union_text = _binding_text(
        {"source_refs": tuple(all_sources), "context_refs": tuple(all_contexts)}
    )
    lines.extend(["", "## 综合判断", ""])
    synthesis = result.get("synthesis")
    if not isinstance(synthesis, dict):
        lines.append(placeholder)
    else:
        judgment = synthesis.get("judgment")
        lines.append(str(judgment) if _nonempty_text(judgment) else placeholder)
        for label, key in (
            ("机会", "opportunities"),
            ("风险", "risks"),
            ("下一步", "next_steps"),
            ("不确定性", "uncertainties"),
        ):
            lines.extend(["", f"### {label}", ""])
            items = _display_list(synthesis, key)
            if items is None:
                lines.append(f"- {placeholder}")
            else:
                lines.extend(f"- {item}" for item in items)
    lines.extend(["", f"证据绑定汇总（本地推导）：{union_text}"])
    return frontmatter + "\n" + "\n".join(lines).rstrip() + "\n"


def publish_draft(value: AssembledInput, artifact: dict[str, object]) -> dict[str, object]:
    """Atomically, idempotently publish exactly one draft plus one sidecar."""
    session = artifact.get("session_identity")
    markdown = artifact.get("markdown")
    result = artifact.get("result")
    catalog = build_quote_catalog(value)
    if (
        not _nonempty_text(session)
        or session != session_identity(value, AUTHORIZATION)
        or artifact.get("quote_catalog_sha256") != catalog.sha256
        or not _nonempty_text(markdown)
        or not isinstance(result, dict)
    ):
        raise FinalAcceptanceExecutionError("artifact_invalid")
    refs = context_card_ids(value)
    if validate_combined_result(result, catalog=catalog, context_ids=refs):
        raise FinalAcceptanceExecutionError("artifact_invalid")
    base = f"fragment-cognition-{value.fragment_id}-{str(session)[:16]}"
    markdown_bytes = str(markdown).encode("utf-8")
    ledger = artifact.get("ledger")
    reservations = ledger.get("reservations") if isinstance(ledger, dict) else None
    call_evidence: list[dict[str, object]] = []
    if isinstance(reservations, list):
        for item in reservations:
            if not isinstance(item, dict):
                continue
            call_evidence.append(
                {
                    key: item[key]
                    for key in (
                        "stage",
                        "provider",
                        "status",
                        "model_claim",
                        "prompt_tokens",
                        "completion_tokens",
                    )
                    if key in item
                }
            )
    # Every evidence ref in the sidecar is generated by local pure
    # functions (quote layer derivation + declared context_refs), never by
    # model-emitted binding fields.
    claim_bindings: dict[str, object] = {}
    claims = result.get("claims")
    assert isinstance(claims, list)
    for claim in claims:
        assert isinstance(claim, dict)
        binding = derived_claim_binding(catalog, claim)
        claim_bindings[str(claim["claim_id"])] = {
            "quote_id": str(claim["quote_id"]),
            "source_refs": list(binding["source_refs"]),
            "context_refs": list(binding["context_refs"]),
        }
    sidecar = {
        "plan_version": PLAN_VERSION,
        "session_identity": session,
        "quote_catalog_sha256": catalog.sha256,
        "fragment_id": value.fragment_id,
        "lifecycle_status": "draft",
        "evidence_level": "unverified",
        "user_confirmed": False,
        "promoted_to_asset": False,
        "paper_independently_verified": False,
        "single_model_single_call": True,
        "draft_sha256": hashlib.sha256(markdown_bytes).hexdigest(),
        "evidence_bindings": {
            "derived_locally": True,
            "claims": claim_bindings,
            "frontier_view": {"source_refs": [value.public_source.source_id]},
        },
        "model_calls": call_evidence,
    }
    payloads = {
        f"{base}.md": markdown_bytes,
        f"{base}.json": (
            json.dumps(sidecar, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
            + "\n"
        ).encode("utf-8"),
    }
    output_dir = value.output_dir
    path_errors = check_local_path_safety(output_dir, expect="dir")
    if path_errors:
        raise FinalAcceptanceExecutionError(f"path_unsafe:{path_errors[0]}")
    if output_dir.exists():
        names = {path.name for path in output_dir.iterdir()}
        if names != set(payloads):
            raise FinalAcceptanceExecutionError("publish_conflict")
        for name, payload in payloads.items():
            path = output_dir / name
            if path.is_symlink() or not path.is_file() or path.read_bytes() != payload:
                raise FinalAcceptanceExecutionError("publish_conflict")
        status = "already_published"
    else:
        parent = output_dir.parent
        prefix = f".{output_dir.name}.staging-"
        if parent.exists():
            # Any staging residue from a previous run — directory, plain file,
            # or symlink — fails closed with zero byte changes; only staging
            # created by this very publish attempt may be cleaned up below.
            for leftover in parent.iterdir():
                if leftover.name.startswith(prefix):
                    raise FinalAcceptanceExecutionError("publish_staging_residue")
        parent.mkdir(parents=True, exist_ok=True)
        staging = Path(tempfile.mkdtemp(prefix=prefix, dir=parent))
        try:
            for name, payload in payloads.items():
                path = staging / name
                path.write_bytes(payload)
                path.chmod(0o600)
            os.replace(staging, output_dir)
        except Exception:
            for path in staging.iterdir():
                path.unlink()
            staging.rmdir()
            raise
        status = "published"
    return {
        "status": status,
        "files": sorted(payloads),
        "draft_sha256": sidecar["draft_sha256"],
    }


def selfcheck() -> dict[str, object]:
    """Pure offline invariants of the frozen plan; no filesystem or network."""
    checks: dict[str, str] = {}
    total_input = sum(budget[1] for budget in _STAGE_BUDGETS.values())
    total_output = sum(budget[2] for budget in _STAGE_BUDGETS.values())
    checks["total_input_limit"] = (
        "ok" if total_input == _TOTAL_INPUT_LIMIT == 10_000 else "failed"
    )
    checks["total_output_limit"] = (
        "ok" if total_output == _TOTAL_OUTPUT_LIMIT == 7_000 else "failed"
    )
    glm_calls = sum(1 for budget in _STAGE_BUDGETS.values() if budget[0] == "glm47")
    deepseek_calls = sum(
        1 for budget in _STAGE_BUDGETS.values() if budget[0] == "deepseek_v4_pro"
    )
    checks["plan_provider_calls"] = (
        "ok"
        if glm_calls == 0
        and deepseek_calls == 1
        and deepseek_calls == _PROVIDER_LIMITS["deepseek_v4_pro"]
        and len(_PROVIDER_LIMITS) == 1
        else "failed"
    )
    profile = SourceProfile(allowed_host="example.com", allowed_path_prefix="/research/")
    checks["url_accepts_clean_https"] = (
        "ok" if not check_public_url("https://example.com/research/a", profile) else "failed"
    )
    bad_urls = (
        "https://example.com/research/a?uid=1",
        "https://example.com/research/a#frag",
        "https://user@example.com/research/a",
        "http://example.com/research/a",
        "https://other.example.net/research/a",
        "https://example.com/other/a",
    )
    checks["url_rejects_drift"] = (
        "ok" if all(check_public_url(url, profile) for url in bad_urls) else "failed"
    )
    status = "ok" if all(result == "ok" for result in checks.values()) else "failed"
    return {"status": status, "checks": checks, "plan_version": PLAN_VERSION}
